from functools import lru_cache

from fastapi import APIRouter, Depends, HTTPException, status
from starlette.concurrency import run_in_threadpool

from app.models.generation import GenerateSQLRequest, GenerateSQLResponse
from app.services.prompt_builder import SQLPromptBuilder
from app.services.llm_service import (
    GeminiLLMService,
    LLMUnavailableError,
    LLMMaxRetriesExceededError,
    LLMResponseParseError,
    LLMServiceError,
)
from app.utils.config import Settings, get_settings
from app.utils.logging import get_logger

logger = get_logger(__name__)
router = APIRouter()


# ---------------------------------------------------------------------------
# Dependency factories — cached per process via lru_cache
# ---------------------------------------------------------------------------

@lru_cache
def get_prompt_builder() -> SQLPromptBuilder:
    return SQLPromptBuilder(get_settings())


@lru_cache
def get_llm_service() -> GeminiLLMService:
    return GeminiLLMService(get_settings())


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.post(
    "/generate-sql",
    response_model=GenerateSQLResponse,
    summary="Generate SQL from a natural language question",
    description=(
        "Accepts a natural language question and the top-K retrieved schema tables "
        "from POST /retrieve, builds a structured prompt, and returns the SQL "
        "generated by Gemini 2.5 Flash together with a confidence score. "
        "SQL is NOT executed at this stage."
    ),
)
async def generate_sql(
    request: GenerateSQLRequest,
    prompt_builder: SQLPromptBuilder = Depends(get_prompt_builder),
    llm_service: GeminiLLMService = Depends(get_llm_service),
    settings: Settings = Depends(get_settings),
) -> GenerateSQLResponse:
    logger.info(
        "generate_sql_request",
        extra={
            "question_length": len(request.question),
            "table_count": len(request.retrieved_tables),
            "tables": [t.table_name for t in request.retrieved_tables],
        },
    )

    # Step 1 — Build the LLM prompt
    try:
        prompt = prompt_builder.build_prompt(
            question=request.question,
            retrieved_tables=request.retrieved_tables,
        )
    except Exception as exc:
        logger.error("prompt_build_failed", extra={"error": str(exc)})
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to build generation prompt.",
        ) from exc

    # Step 2 — Call Gemini (offloaded to thread pool so async loop is not blocked)
    try:
        result = await run_in_threadpool(llm_service.generate, prompt)
    except LLMUnavailableError as exc:
        logger.error("llm_unavailable", extra={"error": str(exc)})
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="LLM service is unavailable. Check GEMINI_API_KEY and model configuration.",
        ) from exc
    except LLMMaxRetriesExceededError as exc:
        logger.error("llm_max_retries_exceeded", extra={"error": str(exc)})
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="LLM service failed after maximum retries. Please try again later.",
        ) from exc
    except LLMResponseParseError as exc:
        logger.error("llm_response_parse_error", extra={"error": str(exc)})
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="LLM returned an unparseable response.",
        ) from exc
    except LLMServiceError as exc:
        logger.error("llm_service_error", extra={"error": str(exc)})
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="SQL generation failed.",
        ) from exc

    logger.info(
        "generate_sql_completed",
        extra={
            "confidence": result.confidence,
            "sql_length": len(result.sql),
            "latency_ms": round(result.latency_ms, 2),
            "attempt": result.attempt,
            "model": settings.gemini_model_name,
        },
    )

    return GenerateSQLResponse(sql=result.sql, confidence=result.confidence)
